title: Prácticas en Azure para ASIR
description: Prácticas de contenidos de 1º de ASIR para realizar en Azure
theme: just-the-docs

url: https://jrpellicer.github.io/azureasir

aux_links:
  Repositorio en GitHub: https://github.com/jrpellicer/azureasir
