title: Prácticas de ASIR en Azure
description: Prácticas de contenidos de 1º de ASIR para realizar en Azure
theme: just-the-docs

url: https://jrpellicer.github.io/azureasir

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
